name: cart-UI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
       contents: read
       packages: write

    defaults:
      run:
        working-directory: retail-store-sample-app/src/cart

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Make mvnw executable
      run: chmod +x ./mvnw
      working-directory: retail-store-sample-app/src/cart   
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  
    - name: Set up Snyk CLI to check for security issues
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb 

    - name: Run Snyk dependency scan
      working-directory: retail-store-sample-app/src/cart
      continue-on-error: true
      run: snyk test --file=pom.xml -d
      env:
       SNYK_TOKEN: ${{ secrets.SNYK}}

    - name: Check Docker
      run: docker --version

    - name: Build Docker image
      working-directory: retail-store-sample-app/src/cart
      env:
       IMAGE_TAG: v${{ github.run_number }}
      run: |
       docker build \
        -t retail-cart:$IMAGE_TAG .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      env:
       IMAGE_TAG: v${{ github.run_number }}
      run: |
        docker tag \
        retail-cart:$IMAGE_TAG \
        ${{ secrets.DOCKER_USERNAME }}/retail-cart:$IMAGE_TAG

    - name: Push Docker image
      env:
       IMAGE_TAG: v${{ github.run_number }}
      run: |
        docker push \
        ${{ secrets.DOCKER_USERNAME }}/retail-cart:$IMAGE_TAG
